FROM registry.redhat.io/rhel8/go-toolset:1.22.9 as builder

WORKDIR /opt/app-root/src

COPY go.mod go.mod
COPY go.sum go.sum
COPY vendor/ vendor/
COPY cmd/ cmd/
COPY pkg/ pkg/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=vendor -o location ./cmd/location/...

FROM registry.access.redhat.com/ubi9-minimal:9.1.0

COPY --from=builder /opt/app-root/src/location /usr/local/bin/location

USER 65532:65532

ENTRYPOINT [ "location" ]